### ISSUE TITLE
Ошибка работы с сокетами на Mac OSX

### ISSUE THREAD

**Issue by stanislavsay** [sidigi/bitrix-docker#2]
Во-первых, спасибо за сборку) Завелась с лету на OSX
Но, к сожалению проверку Битрикс не проходит, ссылаясь на сабж. Я не очень силен в докере, только изучаю. Дополнил свой /etc/hosts двумя строчками
127.0.0.1 ca8ecc8edf60 (ИД контейнера с nginx)
10.100.0.21 ca8ecc8edf60
Но не помогает (((
Как Вы решаете эту проблему?

UPD: проверил на линукс - там все отлично... Видимо проблема возникает, из-за того, что из OSX внутренняя сеть докера не доступна. Это печалит конечно ((( Но, вдруг вы все-таки знаете как это решить?)))

**Comment by sidigi** [comment]
Привет. 
На данный момент как раз пытаюсь решить проблему. Дело в том что у меня под рукой мак оси нет, но есть у сотрудника. Да проблема в том что мак позволяет доступ только по локлхосту, нужно что то сделать с сетью.

Можно попробовать такой конфиг, тут есть поддержка шлюза. К сожалению проверить не могу

```
version: '2'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/nginx/:/var/log/nginx/
    ports:
      - "${NGINX_INTERFACE}:80:80"
    depends_on:
      - php-fpm
      - php-fpm-cli
    networks:
      - bitrix
  php-fpm-cli:
    build:
      context: ./docker
      dockerfile: php-fpm-cli.docker
    volumes:
      - ./www:/var/www/bitrix
    depends_on:
      - mysql
    tty: true
    networks:
      - bitrix
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./www:/var/www/bitrix
      - ./storage/docker/logs/php/:/var/log/php/
    depends_on:
      - mysql
    networks:
      - bitrix
  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33061:3306"
    networks:
      - bitrix
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bitrix
networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1
```
